In [1]:
from collections import namedtuple
import os
import pandas as pd
import sys

In [2]:
class Bracket:
#     It stores a bracket type which is one of [, (, { and position of the bracket

    def __init__(self, bracket, position):
        self.bracket = bracket
        self.position = position

    def match(self, char):
        """Matches given character with the bracket's type."""

        if self.bracket == '[' and char == ']':
            return True
        if self.bracket == '{' and char == '}':
            return True
        if self.bracket == '(' and char == ')':
            return True
        return False


def checker(text):
    stack = []
    for index, char in enumerate(text, start=1):

        if char in ("[", "(", "{"):
            stack.append(Bracket(char, index))

        elif char in ("]", ")", "}"):
            if not stack:
                return index

            top = stack.pop()
            if not top.match(char):
                return index
    if stack:
        top = stack.pop()
        return top.position

    return "Success"


if __name__ == "__main__":
    text = sys.stdin.read().strip("\n")
    print(checker(text))

Success

# test if everything in tests folder passes.

In [3]:
test_path = r'C:\Users\sudhe\Desktop\github_repos\Data-Structures-and-Algorithms-specialization-University-of-California-San-Diego\course 2 - Data Structures\week1_basic_data_structures\check_brackets_in_code\tests'

In [4]:
def test_function():
    df = pd.DataFrame(columns = ['filename','correct ans','our ans'])
    path = test_path
    i = 0
    for filename in os.listdir(path): 
        if filename.endswith('.a'): 
            f = open(path+'/' + filename, 'r') 
            content = f.read()[:-1] #because there is trailing \n at the end. this need to be according to the pattern in output/input file
            f_test = open(path+'/' + filename.partition(".")[0], 'r')
            our_result = checker(f_test.read()) 
#             print('stardard_result: ', content)
#             print('Our_algorithm_result: ', our_result)
            df.loc[i] = [filename.partition(".")[0],content,str(our_result)] #str(our_result) because content is a string. should be changed according to test files
            i+=1
        
    if df['correct ans'].equals(df['our ans']): #check if all the answers are matching
        print('all tests have passed')
    else:
        print('some tests are failing')
    return df

In [5]:
df = test_function()

all tests have passed

In [6]:
df

   filename correct ans  our ans
0        01     Success  Success
1        02     Success  Success
2        03     Success  Success
3        04     Success  Success
4        05     Success  Success
5        06     Success  Success
6        07     Success  Success
7        08     Success  Success
8        09     Success  Success
9        10     Success  Success
10       11     Success  Success
11       12     Success  Success
12       13     Success  Success
13       14           1        1
14       15           1        1
15       16           1        1
16       17           1        1
17       18           1        1
18       19           1        1
19       20           1        1
20       21           3        3
21       22           3        3
22       23           5        5
23       24           5        5
24       25           5        5
25       26           3        3
26       27           1        1
27       28           5        5
28       29           5        5
29       30           7        7
30       31           4        4
31       32           6        6
32       33           3        3
33       34           3        3
34       35           2        2
35       36           1        1
36       37           4        4
37       38           2        2
38       39           4        4
39       40           4        4
40       41           8        8
41       42          13       13
42       43     Success  Success
43       44     Success  Success
44       45     Success  Success
45       46     Success  Success
46       47     Success  Success
47       48     Success  Success
48       49         972      972
49       50          35       35
50       51         174      174
51       52     Success  Success
52       53     Success  Success
53       54     Success  Success